{% set name = "bioimageio.spec" %}
{% set version = "0.5.4.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bioimageio_spec-{{ version }}.tar.gz
  sha256: b5209f745fb9a3cb62c9e53b236d78dd1b05f3c6a2ee596a1091f571fa942212

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - annotated-types >=0.5.0,<1
    - email_validator
    - genericache ==0.4.1
    - imageio
    - loguru
    - markdown
    - numpy >=1.21
    - packaging >=17.0
    - pooch >=1.5,<2
    - pydantic-core
    - pydantic-settings >=2.5,<3
    - pydantic >=2.10.3,<2.12
    - python >={{ python_min }}
    - python-dateutil
    - httpx
    - rich
    - ruyaml
    - tifffile >=2020.7.4
    - tqdm
    - typing-extensions
    - zipp


test:
  imports:
    - bioimageio.spec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: Parser and validator library for BioImage.IO specifications
  dev_url: https://github.com/bioimage-io/spec-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
