{% set name = "bioimageio.spec" %}
{% set version = "0.5.3.post2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioimageio.spec-{{ version }}.tar.gz
  sha256: 44cd5fba32bca3eb13a67172a97b55d565366a5b6073d9db6c30780a875920e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - annotated-types >=0.5.0,<1
    - email_validator
    - imageio
    - loguru
    - numpy >=1.21
    - packaging >=17.0
    - pooch >=1.5,<2
    - pydantic-core
    - pydantic-settings
    - pydantic >=2.6.3,<3
    - python >=3.8
    - python-dateutil
    - python-dotenv
    - requests
    - rich
    - ruyaml
    - tqdm
    - typing-extensions


test:
  imports:
    - bioimageio.spec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: Parser and validator library for BioImage.IO specifications
  dev_url: https://github.com/bioimage-io/spec-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
