{% set name = "bioimageio.spec" %}
{% set version = "0.5.3.3" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bioimageio.spec-{{ version }}.tar.gz
  sha256: da1089305d7d7f37db065a8e06b50956e1471532ee6e99bf6ad72451604858b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - annotated-types >=0.5.0,<1
    - email_validator
    - imageio
    - loguru
    - numpy >=1.21
    - packaging >=17.0
    - pooch >=1.5,<2
    - pydantic-core
    - pydantic-settings
    - pydantic >=2.7.0,<3
    - python >={{ python_min }}
    - python-dateutil
    - requests
    - rich
    - ruyaml
    - tifffile
    - tqdm
    - typing-extensions
    - zipp


test:
  imports:
    - bioimageio.spec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: Parser and validator library for BioImage.IO specifications
  dev_url: https://github.com/bioimage-io/spec-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
