{% set name = "bioimageio.spec" %}
{% set version = "0.5.0.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioimageio.spec-{{ version }}.tar.gz
  sha256: 8e07a7ae0133f7750818b4057aa57d10a5f3319f04d68b831bd037879a910280

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python>=3.8
  run:
    - annotated-types>=0.5.0
    - email_validator
    - imageio
    - loguru
    - numpy>=1.21
    - packaging>=17.0
    - pooch
    - pydantic-settings
    - pydantic>=2.6.3
    - python-dateutil
    - python>=3.8
    - ruyaml
    - tqdm
    - typing-extensions

test:
  imports:
    - bioimageio.spec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: Parser and validator library for BioImage.IO specifications
  dev_url: https://github.com/bioimage-io/spec-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
